### ISSUE TITLE
Hacer que los campos de moneda, estatus y frecuencia no se bloqueen

### ISSUE THREAD

**Issue by 2-che** [LookAtTheMirror/finami-app#14]
Para estos campos se colocan unos datos predeterminados, que se guarde el registro sin tener que actualizar estos campos

**Comment by 2-che** [comment]
Colocarlos como el campo de fecha que no tiene que ser modificado para que sea aceptado por el sistema

**Comment by decode9** [comment]
Corregido en PR #20
