### ISSUE TITLE
No se actualiza el estado financiero

### ISSUE THREAD

**Issue by 2-che** [LookAtTheMirror/finami-app#16]
No se actualiza el estado financiero total al ingresar nuevos registros
![WhatsApp Image 2022-10-18 at 9 33 21 PM](https://user-images.githubusercontent.com/102318848/196576443-eda72c13-5ee2-44bf-a78b-0f87a62b23ff.jpeg)

**nota:** Al no tener ningún dato registrado el valor del estado financiero total debería estar en blanco

**Comment by decode9** [comment]
Corregido en #21
