### ISSUE TITLE
Interacción al cambiar entre secciones

### ISSUE THREAD

**Issue by 2-che** [LookAtTheMirror/finami-app#17]
De ser posible, hacer que el cambio de las secciones de la aplicación (dashboard, ingresos, egresos y perfil) se realicen deslizando hacia los lados. Que esta interacción sea adicional a la ya existe (tap).

**Comment by decode9** [comment]
Cerrado debido a que la libreria utilizada para el navegador tab no tiene esta funcionalidad disponible actualmente, se deja para futuras actualizaciones.
