### ISSUE TITLE
Crear Elemento Ingreso y Egreso , Elementos y Categorias

### ISSUE THREAD

**Issue by djoel95** [LookAtTheMirror/finami-app#24]
Cuando seleccionas que un elemento se paga "Concurrente" en el cuadro donde dice "Monto" deberia decir "Cantidad o N veces al mes" pensar en una mejor palabra.

![image](https://user-images.githubusercontent.com/119460504/204676836-e6dae192-ad6f-4b6a-bb75-1e407d186969.png)

**Comment by decode9** [comment]
resolved
