### ISSUE TITLE
Modificar Elementos 

### ISSUE THREAD

**Issue by djoel95** [LookAtTheMirror/finami-app#26]
Al modificar cualquier elemento en ingreso o egreso genera el siguiente error, recomendacion revisar 

![image](https://user-images.githubusercontent.com/119460504/204680161-4c06bbfc-710f-47ca-b9fb-75d687e2e588.png)
![image](https://user-images.githubusercontent.com/119460504/204680176-2c197348-62a4-4830-b258-0a83fd12273b.png)

**Comment by decode9** [comment]
fixed
