### ISSUE TITLE
Crear Nuevos Elementos

### ISSUE THREAD

**Issue by djoel95** [LookAtTheMirror/finami-app#27]
Al crear un nuevo elemento en ingresos o egresos, se sobrescribe el ultimo elemento agregado 

![image](https://user-images.githubusercontent.com/119460504/204681006-6c797975-794a-4fed-a89b-c9907c679bfc.png)
![image](https://user-images.githubusercontent.com/119460504/204681023-875908c6-9d0c-406c-9f43-4ecbdaf0d762.png)
![image](https://user-images.githubusercontent.com/119460504/204681044-2ddb078f-2bce-4aba-881a-a5c8e1fb1819.png)

**Comment by decode9** [comment]
Fixed
