### ISSUE TITLE
Reporte Financiero

### ISSUE THREAD

**Issue by djoel95** [LookAtTheMirror/finami-app#28]
Al solicitar el reporte de un mes no muestra los datos correctos, adicional que me dio el siguiente error. 
![image](https://user-images.githubusercontent.com/119460504/204681560-15b04a93-3f09-4fa3-a42a-067fed182fb0.png)
![image](https://user-images.githubusercontent.com/119460504/204681572-397f0d3c-76af-4b51-9e35-ec531897acd5.png)

**Comment by decode9** [comment]
resolved
